// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE2CRu_VszYlfFQgeDKqriAS3RKcZHK60',
    appId: '1:283966448367:web:547546ee9ef0f2103cf11a',
    messagingSenderId: '283966448367',
    projectId: 'capybara-b97af',
    authDomain: 'capybara-b97af.firebaseapp.com',
    storageBucket: 'capybara-b97af.firebasestorage.app',
    measurementId: 'G-DWRN81SY3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVzKtLIxNWJGAZzTpyDNjeFocktmK9cgc',
    appId: '1:283966448367:android:6946066bd44c58ba3cf11a',
    messagingSenderId: '283966448367',
    projectId: 'capybara-b97af',
    storageBucket: 'capybara-b97af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn0C0KvLMtRCRWVklIlpXWCUUY7dGd6qw',
    appId: '1:283966448367:ios:bf3609f773ebd5443cf11a',
    messagingSenderId: '283966448367',
    projectId: 'capybara-b97af',
    storageBucket: 'capybara-b97af.firebasestorage.app',
    iosBundleId: 'com.example.capybara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn0C0KvLMtRCRWVklIlpXWCUUY7dGd6qw',
    appId: '1:283966448367:ios:bf3609f773ebd5443cf11a',
    messagingSenderId: '283966448367',
    projectId: 'capybara-b97af',
    storageBucket: 'capybara-b97af.firebasestorage.app',
    iosBundleId: 'com.example.capybara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE2CRu_VszYlfFQgeDKqriAS3RKcZHK60',
    appId: '1:283966448367:web:3e604233e40a77d33cf11a',
    messagingSenderId: '283966448367',
    projectId: 'capybara-b97af',
    authDomain: 'capybara-b97af.firebaseapp.com',
    storageBucket: 'capybara-b97af.firebasestorage.app',
    measurementId: 'G-B9ZVZ3ZYYV',
  );

}